services:
  env-init:
    volumes:
      - ./:/app

  api:
    volumes:
      - ./apps/api:/app/apps/api:ro
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  web:
    volumes:
      - ./apps/web:/app/apps/web:ro
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  game:
    build:
      context: .
      dockerfile: apps/game/Dockerfile
      target: deps
    command: pnpm -C apps/game dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app:rw
      - /app/node_modules
      - /app/apps/game/node_modules
      - /app/packages/db/node_modules

  chat:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  db-init:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro

  cdn:
    volumes:
      - ./deploy/nginx/cdn-local.conf:/etc/nginx/conf.d/default.conf:ro
