services:
  env-init:
    volumes:
      - ./:/app

  api:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  web:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  game:
    build:
      context: .
      dockerfile: apps/game/Dockerfile
      target: deps
    command: pnpm -C apps/game dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app:rw
      - /app/node_modules
      - /app/apps/game/node_modules
      - /app/packages/db/node_modules

  chat:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro
      - ./certs:/app/certs:ro

  migrate:
    volumes:
      - ./apps/shared-assets:/app/apps/shared-assets:ro
