[
{
    "_id": 1,
    "name": "Water's Fury",
    "desc": "A weak, water-based combat spell",
    "type": "combat",
    "lvl": 1,
    "exp": 4,
    "maxDamage": 2,
    "recipe": [
        {
            "itemId": 178,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 2,
    "name": "Nature's Fury",
    "desc": "A weak, natural combat spell",
    "type": "combat",
    "lvl": 6,
    "exp": 8,
    "maxDamage": 4,
    "recipe": [
        {
            "itemId": 178,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 3,
    "name": "Fire's Fury",
    "desc": "A weak, fiery combat spell",
    "type": "combat",
    "lvl": 15,
    "exp": 12,
    "maxDamage": 6,
    "recipe": [
        {
            "itemId": 178,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 4,
    "name": "Hedgecastle Teleport",
    "desc": "Teleports the player to Hedgecastle",
    "type": "teleport",
    "lvl": 24,
    "exp": 25,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 5,
    "name": "aurum minor",
    "desc": "A basic alchemy spell to convert an object into gold",
    "type": "inventory",
    "lvl": 20,
    "exp": 30,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 184,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 6,
    "name": "aurum majora",
    "desc": "An advanced-level alchemy spell to convert an object into gold",
    "type": "inventory",
    "lvl": 60,
    "exp": 70,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 184,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 4
        }
    ],
    "requirements":null
},
{
    "_id": 7,
    "name": "Ictirine Teleport",
    "desc": "Teleports the player to Icterine City",
    "type": "teleport",
    "lvl": 35,
    "exp": 35,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 8,
    "name": "Highcove Teleport",
    "desc": "Teleports the player to High Cove",
    "type": "teleport",
    "lvl": 42,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 9,
    "name": "Water's Rage",
    "desc": "A water-based combat spell",
    "type": "combat",
    "lvl": 18,
    "exp": 15,
    "maxDamage": 8,
    "recipe": [
        {
            "itemId": 179,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 3
        }
    ],
    "requirements":null
},
{
    "_id": 10,
    "name": "Nature's Rage",
    "desc": "A natural combat spell",
    "type": "combat",
    "lvl": 25,
    "exp": 18,
    "maxDamage": 10,
    "recipe": [
        {
            "itemId": 179,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 3
        }
    ],
    "requirements":null
},
{
    "_id": 11,
    "name": "Fire's Rage",
    "desc": "A fiery combat spell",
    "type": "combat",
    "lvl": 32,
    "exp": 21,
    "maxDamage": 12,
    "recipe": [
        {
            "itemId": 179,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 3
        }
    ],
    "requirements":null
},
{
    "_id": 12,
    "name": "musculor reduction",
    "desc": "Reduces a target's strength by 5%",
    "type": "status",
    "lvl": 10,
    "exp": 15,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 180,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 13,
    "name": "oculus reduction",
    "desc": "Reduces a target's accuracy by 5%",
    "type": "status",
    "lvl": 16,
    "exp": 15,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 180,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 14,
    "name": "armada reduction",
    "desc": "Reduces a target's defense by 5%",
    "type": "status",
    "lvl": 23,
    "exp": 15,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 180,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 15,
    "name": "Celadon Teleport",
    "desc": "Teleports the player to Celadon",
    "type": "teleport",
    "lvl": 28,
    "exp": 30,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 180,
            "amount": 2
        }
    ],
    "requirements":null
},
{
    "_id": 16,
    "name": "Anglham Teleport",
    "desc": "Teleports the player to Anglham Castle",
    "type": "teleport",
    "lvl": 47,
    "exp": 45,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 5
        }
    ],
    "requirements":null
},
{
    "_id": 17,
    "name": "Water Obelisk Teleport",
    "desc": "Teleports the player to the Water Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 18,
    "name": "Nature Obelisk Teleport",
    "desc": "Teleports the player to the Nature Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 19,
    "name": "Fire Obelisk Teleport",
    "desc": "Teleports the player to the Fire Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 20,
    "name": "Fury Obelisk Teleport",
    "desc": "Teleports the player to the Fury Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 178,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 21,
    "name": "Energy Obelisk Teleport",
    "desc": "Teleports the player to the Energy Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 180,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 22,
    "name": "Rage Obelisk Teleport",
    "desc": "Teleports the player to the Rage Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 179,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 23,
    "name": "Wizard's Obelisk Teleport",
    "desc": "Teleports the player to the Wizard's Obelisk",
    "type": "teleport",
    "lvl": 40,
    "exp": 40,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 355,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 24,
    "name": "Blood Teleport",
    "desc": "Sacrifices half the player's health to teleport away",
    "type": "teleport",
    "lvl": 1,
    "exp": 0,
    "maxDamage": 0,
    "recipe": [],
    "requirements":null
},
{
    "_id": 25,
    "name": "Dragonsmoke Teleport",
    "desc": "Teleports the player to the Dragonsmoke Island",
    "type": "teleport",
    "lvl": 30,
    "exp": 30,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 5
        }
    ],
    "requirements":[
        {
            "desc":"player needs to have completed Dragonsmoke Island quest",
            "type":"quest",
            "questid":3,
            "checkpoint":15,
            "booleanoperator":null,
            "operator":">="
        }
    ]
},
{
    "_id": 26,
    "name": "Portal Obelisk Teleport",
    "desc": "Teleports the player to the Portal Obelisk",
    "type": "teleport",
    "lvl": 55,
    "exp": 55,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 27,
    "name": "Golden Obelisk Teleport",
    "desc": "Teleports the player to the Golden Obelisk",
    "type": "teleport",
    "lvl": 55,
    "exp": 55,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 184,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 28,
    "name": "Blood Obelisk Teleport",
    "desc": "Teleports the player to the Blood Obelisk",
    "type": "teleport",
    "lvl": 55,
    "exp": 55,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 1
        },
        {
            "itemId": 358,
            "amount": 10
        }
    ],
    "requirements":null
},
{
    "_id": 29,
    "name": "Water's Blood",
    "desc": "A powerful, water-based combat spell",
    "type": "combat",
    "lvl": 59,
    "exp": 30,
    "maxDamage": 14,
    "recipe": [
        {
            "itemId": 358,
            "amount": 1
        },
        {
            "itemId": 176,
            "amount": 5
        }
    ],
    "requirements":null
},
{
    "_id": 30,
    "name": "Nature's Blood",
    "desc": "A powerful, natural combat spell",
    "type": "combat",
    "lvl": 65,
    "exp": 33,
    "maxDamage": 16,
    "recipe": [
        {
            "itemId": 358,
            "amount": 1
        },
        {
            "itemId": 177,
            "amount": 5
        }
    ],
    "requirements":null
},
{
    "_id": 31,
    "name": "Fire's Blood",
    "desc": "A powerful, fiery combat spell",
    "type": "combat",
    "lvl": 71,
    "exp": 37,
    "maxDamage": 18,
    "recipe": [
        {
            "itemId": 358,
            "amount": 1
        },
        {
            "itemId": 175,
            "amount": 5
        }
    ],
    "requirements":null
},
{
    "_id": 32,
    "name": "Outburst",
    "desc": "An explosive combat spell",
    "type": "combat",
    "lvl": 70,
    "exp": 50,
    "maxDamage": 30,
    "splashDamage": {
        "size": 3,
        "damageAmountsFromCenter": [ 1, 0.75, 0.5 ],
        "doesSplashDamageGiveXP": true
    },
    "recipe": [
        {
            "itemId": 175,
            "amount": 10
        },
        {
            "itemId": 178,
            "amount": 4
        },
        {
            "itemId": 179,
            "amount": 3
        },
        {
            "itemId": 358,
            "amount": 2
        }
    ],
    "requirements":[
        {
            "desc":"player needs to have damogui's staff equipped",
            "type":"equippeditem",
            "equipmenttype":"weapon",
            "itemids":[
                487
            ],
            "isequipped":true
        }
    ]
},
{
    "_id": 33,
    "name": "confusion",
    "desc": "Confuses the target",
    "type": "status",
    "lvl": 1,
    "exp": 0,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 180,
            "amount": 1
        },
        {
            "itemId": 355,
            "amount": 1
        }
    ],
    "requirements":null
},
{
    "_id": 34,
    "name": "Cairn Teleport",
    "desc": "Teleports the player to Cairn",
    "type": "teleport",
    "lvl": 56,
    "exp": 60,
    "maxDamage": 0,
    "recipe": [
        {
            "itemId": 181,
            "amount": 2
        },
        {
            "itemId": 176,
            "amount": 2
        }
    ],
    "requirements":null
}
]