-- Add persistenceId to worlds
ALTER TABLE "worlds" ADD COLUMN "persistenceId" INTEGER;
UPDATE "worlds" SET "persistenceId" = "id" WHERE "persistenceId" IS NULL;
ALTER TABLE "worlds" ALTER COLUMN "persistenceId" SET NOT NULL;
ALTER TABLE "worlds" ALTER COLUMN "persistenceId" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
  pg_get_serial_sequence('worlds', 'persistenceId'),
  (SELECT GREATEST(COALESCE(MAX("persistenceId"), 1), 1) FROM "worlds")
);
CREATE INDEX "worlds_persistenceId_idx" ON "worlds"("persistenceId");

-- Resolve default persistenceId (serverId=1 or first world)
DO $$
DECLARE
  default_pid INTEGER;
  any_players BOOLEAN;
BEGIN
  SELECT "persistenceId" INTO default_pid FROM "worlds" WHERE "serverId" = 1;
  IF default_pid IS NULL THEN
    SELECT "persistenceId" INTO default_pid FROM "worlds" ORDER BY "id" LIMIT 1;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM "player_skills"
    UNION ALL SELECT 1 FROM "player_locations"
    UNION ALL SELECT 1 FROM "player_equipment"
    UNION ALL SELECT 1 FROM "player_inventory"
    UNION ALL SELECT 1 FROM "player_state_snapshots"
    UNION ALL SELECT 1 FROM "player_banks"
    UNION ALL SELECT 1 FROM "player_abilities"
    UNION ALL SELECT 1 FROM "player_settings"
    UNION ALL SELECT 1 FROM "player_quests"
  ) INTO any_players;

  IF default_pid IS NULL AND any_players THEN
    RAISE EXCEPTION 'Missing world for persistenceId backfill (serverId=1)';
  END IF;

  -- Add persistenceId to player_skills
  ALTER TABLE "player_skills" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_skills" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_skills" ALTER COLUMN "persistenceId" SET NOT NULL;
  DROP INDEX IF EXISTS "player_skills_userId_skillId_key";
  DROP INDEX IF EXISTS "player_skills_userId_idx";
  CREATE UNIQUE INDEX "player_skills_userId_persistenceId_skillId_key" ON "player_skills"("userId", "persistenceId", "skillId");
  CREATE INDEX "player_skills_userId_persistenceId_idx" ON "player_skills"("userId", "persistenceId");
  CREATE INDEX "player_skills_persistenceId_idx" ON "player_skills"("persistenceId");

  -- Add persistenceId to player_locations
  ALTER TABLE "player_locations" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_locations" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_locations" ALTER COLUMN "persistenceId" SET NOT NULL;
  DROP INDEX IF EXISTS "player_locations_userId_key";
  DROP INDEX IF EXISTS "player_locations_userId_idx";
  CREATE UNIQUE INDEX "player_locations_userId_persistenceId_key" ON "player_locations"("userId", "persistenceId");
  CREATE INDEX "player_locations_userId_persistenceId_idx" ON "player_locations"("userId", "persistenceId");
  CREATE INDEX "player_locations_persistenceId_idx" ON "player_locations"("persistenceId");

  -- Add persistenceId to player_equipment
  ALTER TABLE "player_equipment" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_equipment" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_equipment" ALTER COLUMN "persistenceId" SET NOT NULL;
  DROP INDEX IF EXISTS "player_equipment_userId_slot_key";
  DROP INDEX IF EXISTS "player_equipment_userId_idx";
  CREATE UNIQUE INDEX "player_equipment_userId_persistenceId_slot_key" ON "player_equipment"("userId", "persistenceId", "slot");
  CREATE INDEX "player_equipment_userId_persistenceId_idx" ON "player_equipment"("userId", "persistenceId");
  CREATE INDEX "player_equipment_persistenceId_idx" ON "player_equipment"("persistenceId");

  -- Add persistenceId to player_inventory
  ALTER TABLE "player_inventory" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_inventory" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_inventory" ALTER COLUMN "persistenceId" SET NOT NULL;
  DROP INDEX IF EXISTS "player_inventory_userId_slot_key";
  DROP INDEX IF EXISTS "player_inventory_userId_idx";
  DROP INDEX IF EXISTS "player_inventory_userId_slot_idx";
  CREATE UNIQUE INDEX "player_inventory_userId_persistenceId_slot_key" ON "player_inventory"("userId", "persistenceId", "slot");
  CREATE INDEX "player_inventory_userId_persistenceId_idx" ON "player_inventory"("userId", "persistenceId");
  CREATE INDEX "player_inventory_persistenceId_idx" ON "player_inventory"("persistenceId");
  CREATE INDEX "player_inventory_userId_persistenceId_slot_idx" ON "player_inventory"("userId", "persistenceId", "slot");

  -- Add persistenceId to player_state_snapshots
  ALTER TABLE "player_state_snapshots" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_state_snapshots" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_state_snapshots" ALTER COLUMN "persistenceId" SET NOT NULL;
  ALTER TABLE "player_state_snapshots" DROP CONSTRAINT IF EXISTS "player_state_snapshots_pkey";
  ALTER TABLE "player_state_snapshots" ADD CONSTRAINT "player_state_snapshots_pkey" PRIMARY KEY ("userId", "persistenceId");
  CREATE INDEX "player_state_snapshots_userId_persistenceId_idx" ON "player_state_snapshots"("userId", "persistenceId");
  CREATE INDEX "player_state_snapshots_persistenceId_idx" ON "player_state_snapshots"("persistenceId");

  -- Add persistenceId to player_banks
  ALTER TABLE "player_banks" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_banks" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_banks" ALTER COLUMN "persistenceId" SET NOT NULL;
  ALTER TABLE "player_banks" DROP CONSTRAINT IF EXISTS "player_banks_pkey";
  ALTER TABLE "player_banks" ADD CONSTRAINT "player_banks_pkey" PRIMARY KEY ("userId", "persistenceId");
  CREATE INDEX "player_banks_userId_persistenceId_idx" ON "player_banks"("userId", "persistenceId");
  CREATE INDEX "player_banks_persistenceId_idx" ON "player_banks"("persistenceId");

  -- Add persistenceId to player_abilities
  ALTER TABLE "player_abilities" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_abilities" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_abilities" ALTER COLUMN "persistenceId" SET NOT NULL;
  ALTER TABLE "player_abilities" DROP CONSTRAINT IF EXISTS "player_abilities_pkey";
  ALTER TABLE "player_abilities" ADD CONSTRAINT "player_abilities_pkey" PRIMARY KEY ("userId", "persistenceId");
  CREATE INDEX "player_abilities_userId_persistenceId_idx" ON "player_abilities"("userId", "persistenceId");
  CREATE INDEX "player_abilities_persistenceId_idx" ON "player_abilities"("persistenceId");

  -- Add persistenceId to player_settings
  ALTER TABLE "player_settings" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_settings" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_settings" ALTER COLUMN "persistenceId" SET NOT NULL;
  ALTER TABLE "player_settings" DROP CONSTRAINT IF EXISTS "player_settings_pkey";
  ALTER TABLE "player_settings" ADD CONSTRAINT "player_settings_pkey" PRIMARY KEY ("userId", "persistenceId");
  CREATE INDEX "player_settings_userId_persistenceId_idx" ON "player_settings"("userId", "persistenceId");
  CREATE INDEX "player_settings_persistenceId_idx" ON "player_settings"("persistenceId");

  -- Add persistenceId to player_quests
  ALTER TABLE "player_quests" ADD COLUMN "persistenceId" INTEGER;
  UPDATE "player_quests" SET "persistenceId" = default_pid WHERE "persistenceId" IS NULL;
  ALTER TABLE "player_quests" ALTER COLUMN "persistenceId" SET NOT NULL;
  DROP INDEX IF EXISTS "player_quests_userId_questId_key";
  DROP INDEX IF EXISTS "player_quests_userId_idx";
  DROP INDEX IF EXISTS "player_quests_userId_questId_idx";
  CREATE UNIQUE INDEX "player_quests_userId_persistenceId_questId_key" ON "player_quests"("userId", "persistenceId", "questId");
  CREATE INDEX "player_quests_userId_persistenceId_idx" ON "player_quests"("userId", "persistenceId");
  CREATE INDEX "player_quests_persistenceId_idx" ON "player_quests"("persistenceId");
  CREATE INDEX "player_quests_userId_persistenceId_questId_idx" ON "player_quests"("userId", "persistenceId", "questId");

  -- Add persistenceId to online_users
  ALTER TABLE "online_users" ADD COLUMN IF NOT EXISTS "persistenceId" INTEGER NOT NULL DEFAULT 1;
  DROP INDEX IF EXISTS "online_users_userId_key";
  CREATE UNIQUE INDEX IF NOT EXISTS "online_users_userId_persistenceId_key" ON "online_users"("userId", "persistenceId");
END $$;
