server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # Try to serve the exact file requested
    # If it fails, fallback to stripping the hash from the filename
    location /static/ {
        try_files $uri @strip_hash;
    }

    # Match formats like filename.123ab.ext or filename.7.ext and serve filename.ext
    location @strip_hash {
        rewrite ^/static/(.*)\.[a-fA-F0-9]+\.(.*)$ /static/$1.$2 last;
        return 404;
    }
}
